//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryBreakDown.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalaryBreakDown.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input detected. Valid values for Pay Frequency are.
        /// </summary>
        internal static string SalaryBreakDownManager_BadInputFrequency {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_BadInputFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input detected. Terminating....
        /// </summary>
        internal static string SalaryBreakDownManager_BadInputGeneral {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_BadInputGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative income is not supported. Terminating....
        /// </summary>
        internal static string SalaryBreakDownManager_BadInputNegativeIncome {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_BadInputNegativeIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Repair Levy:.
        /// </summary>
        internal static string SalaryBreakDownManager_BudgetRepairLevy {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_BudgetRepairLevy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions:.
        /// </summary>
        internal static string SalaryBreakDownManager_DeductionsHeader {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_DeductionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Press any key to end...&quot;.
        /// </summary>
        internal static string SalaryBreakDownManager_End {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your pay frequency.
        /// </summary>
        internal static string SalaryBreakDownManager_EnterPayFrequency {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_EnterPayFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your salary package amount: .
        /// </summary>
        internal static string SalaryBreakDownManager_EnterSalary {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_EnterSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross package:.
        /// </summary>
        internal static string SalaryBreakDownManager_GrossIncome {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_GrossIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Tax:.
        /// </summary>
        internal static string SalaryBreakDownManager_IncomeTax {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_IncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicare Levy:.
        /// </summary>
        internal static string SalaryBreakDownManager_MedicareLevy {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_MedicareLevy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net income:.
        /// </summary>
        internal static string SalaryBreakDownManager_NetIncome {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_NetIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value too large. Terminating....
        /// </summary>
        internal static string SalaryBreakDownManager_OverFlowEx {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_OverFlowEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay packet:.
        /// </summary>
        internal static string SalaryBreakDownManager_PayPacket {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_PayPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating salary details....
        /// </summary>
        internal static string SalaryBreakDownManager_ProcessingMsg {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_ProcessingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superannuation:.
        /// </summary>
        internal static string SalaryBreakDownManager_Super {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_Super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable income:.
        /// </summary>
        internal static string SalaryBreakDownManager_TaxableIncome {
            get {
                return ResourceManager.GetString("SalaryBreakDownManager_TaxableIncome", resourceCulture);
            }
        }
    }
}
